// <auto-generated />
using System;
using Lynx.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lynx.DbMigration.SqlServer.Migrations
{
    [DbContext(typeof(LynxDbContext))]
    [Migration("20210313203825_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lynx.Domain.Entities.Bill", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tbl_Bill","dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Code = "Globe",
                            IsEnabled = true,
                            LongDesc = "Globe",
                            ShortDesc = "Globe"
                        },
                        new
                        {
                            ID = (short)2,
                            Code = "Meralco",
                            IsEnabled = true,
                            LongDesc = "Meralco",
                            ShortDesc = "Meralco"
                        },
                        new
                        {
                            ID = (short)3,
                            Code = "Home Loan Amortization",
                            IsEnabled = true,
                            LongDesc = "Home Loan Amortization",
                            ShortDesc = "Home Loan Amortization"
                        },
                        new
                        {
                            ID = (short)4,
                            Code = "Car Loan Amortization",
                            IsEnabled = true,
                            LongDesc = "Car Loan Amortization",
                            ShortDesc = "Car Loan Amortization"
                        },
                        new
                        {
                            ID = (short)5,
                            Code = "Credit Card",
                            IsEnabled = true,
                            LongDesc = "Credit Card",
                            ShortDesc = "Credit Card"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillProvider", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<string>("LongDesc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("ProviderTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProviderTypeID");

                    b.ToTable("tbl_BillProvider","dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            BillID = (short)1,
                            ProviderTypeID = (short)3
                        },
                        new
                        {
                            ID = (short)2,
                            BillID = (short)2,
                            ProviderTypeID = (short)3
                        },
                        new
                        {
                            ID = (short)3,
                            BillID = (short)3,
                            ProviderTypeID = (short)1
                        },
                        new
                        {
                            ID = (short)4,
                            BillID = (short)4,
                            ProviderTypeID = (short)1
                        },
                        new
                        {
                            ID = (short)5,
                            BillID = (short)5,
                            LongDesc = "BDO",
                            ProviderTypeID = (short)3,
                            ShortDesc = "BDO"
                        },
                        new
                        {
                            ID = (short)6,
                            BillID = (short)5,
                            LongDesc = "Metrobank",
                            ProviderTypeID = (short)3,
                            ShortDesc = "Metrobank"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillSetting", b =>
                {
                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("BillID", "Code");

                    b.ToTable("tbl_BillSetting","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.Email", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool?>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_Email","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailAttachment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<long>("EmailID")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EmailID");

                    b.ToTable("tbl_EmailAttachment","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailBody", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_EmailBody","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailPart", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EmailID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EmailID");

                    b.ToTable("tbl_EmailPart","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailWorker", b =>
                {
                    b.Property<short>("ID")
                        .HasColumnType("smallint");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.HasKey("ID");

                    b.ToTable("tbl_EmailWorker","dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromGlobeEmailCmdHandler"
                        },
                        new
                        {
                            ID = (short)5,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromBDOCmdHandler"
                        },
                        new
                        {
                            ID = (short)6,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromMetrobankCmdHandler"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationConfiguration", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("N_UserBillTrackingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("N_UserBillTrackingUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserBillTrackingID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("N_UserBillTrackingID", "N_UserBillTrackingUserID");

                    b.ToTable("tbl_NotificationConfiguration","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_NotificationTemplate","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderType", b =>
                {
                    b.Property<short>("ID")
                        .HasColumnType("smallint");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("tbl_ProviderType","dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            LongDesc = "Scheduled",
                            ShortDesc = "Scheduled"
                        },
                        new
                        {
                            ID = (short)2,
                            LongDesc = "API",
                            ShortDesc = "API"
                        },
                        new
                        {
                            ID = (short)3,
                            LongDesc = "Email",
                            ShortDesc = "Email"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigEmail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigEmail","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigScheduler", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<short?>("DayFrequency")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LongDesc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShortDesc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<short?>("SkipTimes")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigScheduler","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigWebService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigWebService","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.SchedulerEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeneratedUserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("TrackBillSchedulerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TrackBillSchedulerID");

                    b.ToTable("tbl_SchedulerEntry","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBill", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LongDesc")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<short>("ProviderTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID", "UserID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProviderTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_TrackBill","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBillSetting", b =>
                {
                    b.Property<Guid>("TrackBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("TrackBillID", "UserID", "Code");

                    b.ToTable("tbl_TrackBillSetting","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("tbl_User","dbo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            FirstName = "Admin",
                            LastName = "Admin"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            FirstName = "Vincent",
                            LastName = "Dagpin"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBill", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<Guid>("TrackBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("TrackBillID", "UserID");

                    b.ToTable("tbl_UserBill","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillAttachment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillID");

                    b.ToTable("tbl_UserBillAttachment","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPayment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillID");

                    b.ToTable("tbl_UserBillPayment","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPaymentTransaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserBillPaymentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillPaymentID");

                    b.ToTable("tbl_UserBillPaymentTransaction","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TemporaryPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_UserLogin","dbo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsTemporaryPassword = true,
                            Password = new byte[] { 217, 202, 150, 25, 117, 221, 121, 108, 37, 105, 80, 196, 244, 39, 65, 219, 215, 163, 50, 198, 193, 228, 162, 123, 181, 60, 246, 155, 163, 199, 37, 50 },
                            Salt = new byte[] { 48, 48, 48, 48, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49 },
                            TemporaryPassword = "k4m0t3",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsTemporaryPassword = true,
                            Password = new byte[] { 9, 238, 26, 39, 21, 0, 163, 101, 247, 77, 240, 232, 43, 49, 198, 12, 240, 157, 218, 92, 107, 1, 52, 133, 11, 6, 230, 247, 114, 49, 127, 182 },
                            Salt = new byte[] { 48, 48, 48, 48, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 50 },
                            TemporaryPassword = "k4m0t3",
                            Username = "vgdagpin"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceivedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_UserNotification","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_UserSession","dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillProvider", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", null)
                        .WithMany("N_BillProviders")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.ProviderType", "N_ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillSetting", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", null)
                        .WithMany("N_BillSettings")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailAttachment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", null)
                        .WithMany("N_Attachments")
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailBody", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", "N_Email")
                        .WithOne("N_Body")
                        .HasForeignKey("Lynx.Domain.Entities.EmailBody", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailPart", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", null)
                        .WithMany("N_Headers")
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailWorker", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.BillProvider", null)
                        .WithOne("N_EmailWorker")
                        .HasForeignKey("Lynx.Domain.Entities.EmailWorker", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationConfiguration", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.TrackBill", "N_UserBillTracking")
                        .WithMany("N_NotificationConfigurations")
                        .HasForeignKey("N_UserBillTrackingID", "N_UserBillTrackingUserID");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigEmail", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigEmail")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigEmail", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigScheduler", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigScheduler")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigScheduler", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigWebService", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigWebService")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigWebService", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.SchedulerEntry", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.ProviderTypeConfigScheduler", null)
                        .WithMany("N_ScheduleEntries")
                        .HasForeignKey("TrackBillSchedulerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBill", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", "N_Bill")
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.ProviderType", "N_ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBillSetting", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithMany("N_TrackBillSettings")
                        .HasForeignKey("TrackBillID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBill", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", "N_TrackBill")
                        .WithMany()
                        .HasForeignKey("TrackBillID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillAttachment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBill", null)
                        .WithMany("N_Attachments")
                        .HasForeignKey("UserBillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPayment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBill", null)
                        .WithMany("N_UserBillPayments")
                        .HasForeignKey("UserBillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPaymentTransaction", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBillPayment", null)
                        .WithMany("N_UserBillPaymentTransactions")
                        .HasForeignKey("UserBillPaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "User")
                        .WithOne("UserLogin")
                        .HasForeignKey("Lynx.Domain.Entities.UserLogin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
