// <auto-generated />
using System;
using Lynx.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lynx.DbMigration.SqlServer.Migrations
{
    [DbContext(typeof(LynxDbContext))]
    [Migration("20210319003141_TextTemplate")]
    partial class TextTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lynx.Domain.Entities.Bill", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tbl_Bill", "dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            Code = "Globe",
                            IsEnabled = true,
                            LongDesc = "Globe",
                            ShortDesc = "Globe"
                        },
                        new
                        {
                            ID = (short)2,
                            Code = "Meralco",
                            IsEnabled = true,
                            LongDesc = "Meralco",
                            ShortDesc = "Meralco"
                        },
                        new
                        {
                            ID = (short)3,
                            Code = "Home Loan Amortization",
                            IsEnabled = true,
                            LongDesc = "Home Loan Amortization",
                            ShortDesc = "Home Loan Amortization"
                        },
                        new
                        {
                            ID = (short)4,
                            Code = "Car Loan Amortization",
                            IsEnabled = true,
                            LongDesc = "Car Loan Amortization",
                            ShortDesc = "Car Loan Amortization"
                        },
                        new
                        {
                            ID = (short)5,
                            Code = "Credit Card",
                            IsEnabled = true,
                            LongDesc = "Credit Card",
                            ShortDesc = "Credit Card"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillPaymentStepsTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<string>("Keywords")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("BillID");

                    b.ToTable("tbl_BillPaymentStepsTemplate", "dbo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BillID = (short)3,
                            Keywords = "7/11,711",
                            LongDesc = "Just kidding, see below very long instructions",
                            ShortDesc = "Go to nearest 7/11, ask cashier for instructions lol",
                            Title = "7/11"
                        },
                        new
                        {
                            ID = 2,
                            BillID = (short)3,
                            Keywords = "e-wallet,ewallet,wallet,gcash",
                            LongDesc = "See below very long instructions",
                            ShortDesc = "Payment using GCash, follow this instruction",
                            Title = "GCash"
                        },
                        new
                        {
                            ID = 3,
                            BillID = (short)3,
                            Keywords = "e-wallet,ewallet,wallet,paymaya",
                            LongDesc = "See below very long instructions",
                            ShortDesc = "Payment using Paymaya, follow this instruction",
                            Title = "Paymaya"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillProvider", b =>
                {
                    b.Property<short>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<string>("LongDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("ProviderTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProviderTypeID");

                    b.ToTable("tbl_BillProvider", "dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            BillID = (short)1,
                            ProviderTypeID = (short)3
                        },
                        new
                        {
                            ID = (short)2,
                            BillID = (short)2,
                            ProviderTypeID = (short)3
                        },
                        new
                        {
                            ID = (short)3,
                            BillID = (short)3,
                            ProviderTypeID = (short)1
                        },
                        new
                        {
                            ID = (short)4,
                            BillID = (short)4,
                            ProviderTypeID = (short)1
                        },
                        new
                        {
                            ID = (short)5,
                            BillID = (short)5,
                            LongDesc = "BDO",
                            ProviderTypeID = (short)3,
                            ShortDesc = "BDO"
                        },
                        new
                        {
                            ID = (short)6,
                            BillID = (short)5,
                            LongDesc = "Metrobank",
                            ProviderTypeID = (short)3,
                            ShortDesc = "Metrobank"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillSetting", b =>
                {
                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BillID", "Code");

                    b.ToTable("tbl_BillSetting", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.Email", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CC")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtractedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("To")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("tbl_Email", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailAttachment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("EmailID")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EmailID");

                    b.ToTable("tbl_EmailAttachment", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailBody", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Html")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Raw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_EmailBody", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailExtract", b =>
                {
                    b.Property<long>("EmailID")
                        .HasColumnType("bigint");

                    b.Property<short>("EmailWorkerID")
                        .HasColumnType("smallint");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmailID", "EmailWorkerID", "Key");

                    b.HasIndex("EmailWorkerID");

                    b.ToTable("tbl_EmailExtract", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailPart", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EmailID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EmailID");

                    b.ToTable("tbl_EmailPart", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailWorker", b =>
                {
                    b.Property<short>("ID")
                        .HasColumnType("smallint");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ID");

                    b.ToTable("tbl_EmailWorker", "dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromGlobeEmailCmdHandler"
                        },
                        new
                        {
                            ID = (short)5,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromBDOCmdHandler"
                        },
                        new
                        {
                            ID = (short)6,
                            AssemblyName = "Lynx.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            TypeName = "Lynx.Application.Handlers.Commands.EmailWorkerCmds.ReadUserBillFromMetrobankCmdHandler"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.FirebaseToken", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("tbl_FirebaseToken", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationConfiguration", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScheduled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("N_UserBillTrackingID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("N_UserBillTrackingUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserBillTrackingID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("N_UserBillTrackingID", "N_UserBillTrackingUserID");

                    b.ToTable("tbl_NotificationConfiguration", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_NotificationTemplate", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderType", b =>
                {
                    b.Property<short>("ID")
                        .HasColumnType("smallint");

                    b.Property<string>("LongDesc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("tbl_ProviderType", "dbo");

                    b.HasData(
                        new
                        {
                            ID = (short)1,
                            LongDesc = "Scheduled",
                            ShortDesc = "Scheduled"
                        },
                        new
                        {
                            ID = (short)2,
                            LongDesc = "API",
                            ShortDesc = "API"
                        },
                        new
                        {
                            ID = (short)3,
                            LongDesc = "Email",
                            ShortDesc = "Email"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigEmail", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientEmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverEmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigEmail", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigScheduler", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<short?>("DayFrequency")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frequency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LongDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("SkipTimes")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigScheduler", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigWebService", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("ID", "UserID")
                        .IsUnique();

                    b.ToTable("tbl_ProviderTypeConfigWebService", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.SchedulerEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GeneratedUserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrackBillSchedulerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("TrackBillSchedulerID");

                    b.ToTable("tbl_SchedulerEntry", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TextTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("Code", "RecordStatus")
                        .IsUnique()
                        .HasFilter("[RecordStatus] = 'Active'");

                    b.ToTable("tbl_TextTemplate", "dbo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "PayWithLynxTOS",
                            Content = "Test",
                            RecordStatus = "Active",
                            Title = "Pay with Lynx Terms of Service",
                            UpdatedOn = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBill", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("BillID")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LongDesc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("ProviderTypeID")
                        .HasColumnType("smallint");

                    b.Property<string>("ShortDesc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID", "UserID");

                    b.HasIndex("BillID");

                    b.HasIndex("ProviderTypeID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_TrackBill", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBillSetting", b =>
                {
                    b.Property<Guid>("TrackBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TrackBillID", "UserID", "Code");

                    b.ToTable("tbl_TrackBillSetting", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("tbl_User", "dbo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            FirstName = "Admin",
                            LastName = "Admin"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            FirstName = "Vincent",
                            LastName = "Dagpin"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBill", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TrackBillID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.HasIndex("TrackBillID", "UserID");

                    b.ToTable("tbl_UserBill", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillAttachment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillID");

                    b.ToTable("tbl_UserBillAttachment", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPayment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(20,6)");

                    b.Property<DateTime?>("PaidOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserBillID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillID");

                    b.ToTable("tbl_UserBillPayment", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPaymentTransaction", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserBillPaymentID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserBillPaymentID");

                    b.ToTable("tbl_UserBillPaymentTransaction", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TemporaryPassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_UserLogin", "dbo");

                    b.HasData(
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000001"),
                            IsTemporaryPassword = true,
                            Password = new byte[] { 217, 202, 150, 25, 117, 221, 121, 108, 37, 105, 80, 196, 244, 39, 65, 219, 215, 163, 50, 198, 193, 228, 162, 123, 181, 60, 246, 155, 163, 199, 37, 50 },
                            Salt = new byte[] { 48, 48, 48, 48, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 49 },
                            TemporaryPassword = "k4m0t3",
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("00000000-0000-0000-0000-000000000002"),
                            IsTemporaryPassword = true,
                            Password = new byte[] { 9, 238, 26, 39, 21, 0, 163, 101, 247, 77, 240, 232, 43, 49, 198, 12, 240, 157, 218, 92, 107, 1, 52, 133, 11, 6, 230, 247, 114, 49, 127, 182 },
                            Salt = new byte[] { 48, 48, 48, 48, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 45, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 50 },
                            TemporaryPassword = "k4m0t3",
                            Username = "vgdagpin"
                        });
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserNotification", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_UserNotification", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionID");

                    b.HasIndex("UserID");

                    b.ToTable("tbl_UserSession", "dbo");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillPaymentStepsTemplate", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", null)
                        .WithMany("N_PaymentStepsTemplates")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillProvider", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", null)
                        .WithMany("N_BillProviders")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.ProviderType", "N_ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N_ProviderType");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillSetting", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", null)
                        .WithMany("N_BillSettings")
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailAttachment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", null)
                        .WithMany("N_Attachments")
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailBody", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", "N_Email")
                        .WithOne("N_Body")
                        .HasForeignKey("Lynx.Domain.Entities.EmailBody", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N_Email");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailExtract", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", null)
                        .WithMany("N_Extracts")
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.EmailWorker", null)
                        .WithMany()
                        .HasForeignKey("EmailWorkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailPart", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Email", null)
                        .WithMany("N_Headers")
                        .HasForeignKey("EmailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.EmailWorker", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.BillProvider", null)
                        .WithOne("N_EmailWorker")
                        .HasForeignKey("Lynx.Domain.Entities.EmailWorker", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.FirebaseToken", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.NotificationConfiguration", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.TrackBill", "N_UserBillTracking")
                        .WithMany("N_NotificationConfigurations")
                        .HasForeignKey("N_UserBillTrackingID", "N_UserBillTrackingUserID");

                    b.Navigation("N_UserBillTracking");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigEmail", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigEmail")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigEmail", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigScheduler", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigScheduler")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigScheduler", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigWebService", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithOne("N_ProviderTypeConfigWebService")
                        .HasForeignKey("Lynx.Domain.Entities.ProviderTypeConfigWebService", "ID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.SchedulerEntry", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.ProviderTypeConfigScheduler", null)
                        .WithMany("N_ScheduleEntries")
                        .HasForeignKey("TrackBillSchedulerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBill", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.Bill", "N_Bill")
                        .WithMany()
                        .HasForeignKey("BillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.ProviderType", "N_ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N_Bill");

                    b.Navigation("N_ProviderType");

                    b.Navigation("N_User");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBillSetting", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.TrackBill", null)
                        .WithMany("N_TrackBillSettings")
                        .HasForeignKey("TrackBillID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBill", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lynx.Domain.Entities.TrackBill", "N_TrackBill")
                        .WithMany("N_UserBills")
                        .HasForeignKey("TrackBillID", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N_TrackBill");

                    b.Navigation("N_User");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillAttachment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBill", null)
                        .WithMany("N_Attachments")
                        .HasForeignKey("UserBillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPayment", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBill", null)
                        .WithMany("N_UserBillPayments")
                        .HasForeignKey("UserBillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPaymentTransaction", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.UserBillPayment", null)
                        .WithMany("N_UserBillPaymentTransactions")
                        .HasForeignKey("UserBillPaymentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "User")
                        .WithOne("UserLogin")
                        .HasForeignKey("Lynx.Domain.Entities.UserLogin", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserNotification", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "N_User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("N_User");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Lynx.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.Bill", b =>
                {
                    b.Navigation("N_BillProviders");

                    b.Navigation("N_BillSettings");

                    b.Navigation("N_PaymentStepsTemplates");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.BillProvider", b =>
                {
                    b.Navigation("N_EmailWorker");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.Email", b =>
                {
                    b.Navigation("N_Attachments");

                    b.Navigation("N_Body");

                    b.Navigation("N_Extracts");

                    b.Navigation("N_Headers");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.ProviderTypeConfigScheduler", b =>
                {
                    b.Navigation("N_ScheduleEntries");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.TrackBill", b =>
                {
                    b.Navigation("N_NotificationConfigurations");

                    b.Navigation("N_ProviderTypeConfigEmail");

                    b.Navigation("N_ProviderTypeConfigScheduler");

                    b.Navigation("N_ProviderTypeConfigWebService");

                    b.Navigation("N_TrackBillSettings");

                    b.Navigation("N_UserBills");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.User", b =>
                {
                    b.Navigation("UserLogin");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBill", b =>
                {
                    b.Navigation("N_Attachments");

                    b.Navigation("N_UserBillPayments");
                });

            modelBuilder.Entity("Lynx.Domain.Entities.UserBillPayment", b =>
                {
                    b.Navigation("N_UserBillPaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
